### ISSUE TITLE
Erreur à l'étape 7

### ISSUE THREAD

**Issue by antoinemichaud** [antoinemichaud/tennisevolution#22]
Unhandled rejection SyntaxError: Unexpected token <
    at Object.parse (native)
    at /home/dolounet/dev/xke/2015/03/tennis-challenger/server/routes.js:50:19
    at tryCatcher (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/promise.js:505:31)
    at Promise._settlePromiseAt (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/home/dolounet/dev/xke/2015/03/tennis-challenger/server/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:367:17)

**Comment by antoinemichaud** [comment]
Je n'ai pas réussi à reproduire le bug. Peut-être que c'était dû à ma version de serveur java.
